### ISSUE TITLE
Connect errors 

### ISSUE THREAD

**Issue by painterzeou** [jzr-supove/AutoBIRDTon#1]
After open it and add auth key 

 python3 main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/mymy/autobirdton/gui.py", line 227, in connect_websocket
    self.game_client = GameClient(tg_data=auth_key_dict, ui=self)
  File "/home/mymy/autobirdton/client.py", line 81, in __init__
    self.ADS_URL = self.ADS_URL.format(user_id=temp["user"]["id"], chat_instance=temp["chat_instance"])
KeyError: 'chat_instance'

**Comment by jzr-supove** [comment]
Seems like it got updated and `"chat_instance"` is not available anymore, and ad urls stopped accepting this parameter also.
I've pushed an update, should be working now ✅

Do `git pull` to update

Let me know if it works for you

**Comment by painterzeou** [comment]
It worked thanks so much

**Comment by jzr-supove** [comment]
Thanks for reporting this issue. It's now resolved
